# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 807981c71dcc516e998ebe8b8ababd82238581b875dd50b4722d68cbce04fd15c4898f10b56fea15a16e0cec687c46c81fbbbe9b22e74ba91ed06025e9908e5c

test:
  secret_key_base: 92d9eb088319207b5bb0a090aeb22f9488d6ca48ac323279e5c362da1ccd3493ceb49cf25fa69ab28a6afb9594d4ed80c1ddfcddf54e5e019348b67048b98df7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
